Integracion insightMetrics
mercadopago/sdk-java pull request #108
Opened 2020-01-28 18:41 UTC by rafgod

## Cambios realizados para el feature:
 * Se agregaron algunos parametros mas para armar el request de metrics
 * Se hicieron casos de pruebas de llamado a insightLight y metrics

## Cambios generales
 * Integracion Insight
 
## Issues cerrados
 * Closes #XX
 

## Checklist validación PR:

- [* ] Título y descripción clara del PR
- [* ] Tests de mi funcionalidad 
- [ ] Documentación de mi funcionalidad
- [ *] Tests ejecutados y pasados
- [ ] Branch Coverage >= 80%

2020-01-30 20:22 UTC, rkuzner requested changes

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +public class InsightDataManager {
esta clase debería ser un singleton y tener la responsabilidad de llamar al back-end para:
- consultar traffic-light
- enviar métricas

además exponer métodos de instancia (no estáticos) para ser consultados por stats() que digan:
- si esta o no habilitada para mandar métricas
- si un endpoint esta o no en la white-list
- enviar métricas

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightConnectionManager.java
> +public class InsightConnectionManager {
tal como hablamos, debe ir dentro de `InsightsDataManager()`

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/Stats.java
> +    static final String INSIGHT_DEFAULT_BASE_URL = "https://events.mercadopago.com/";
ya que estamos, las constantes se van dentro de `InsightsDataManager()`

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/Stats.java
> +    public static boolean isEndpointInWhiteList(TrafficLightResponse trafficLight, String endpoint) {
mover este método a público de instancia de `InsightDataManager()`

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/TrafficLightManager.java
> +public class TrafficLightManager {
tal como hablamos, debe ir dentro de `InsightsDataManager()`

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/TrafficLightManager.java
> +    }
incluir el TTL para que ante una falla solo consulte nuevamente al back-end luego de 10 minutos (600 segundos)

2020-01-30 20:22 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            ConnectionInfo connectionInfo = new ConnectionInfo.Builder().withUserAgent(request.getLastHeader(HTTP.USER_AGENT)!=null?request.getLastHeader(HTTP.USER_AGENT).getValue():"")
solo usaría `withUserAgent()` cuando tengo valor y no guardaría string vacío.

2020-01-31 03:08 UTC, rafgod-ML commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +public class InsightDataManager {
Listo

2020-01-31 15:56 UTC, rkuzner requested changes

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    public static  InsightDataManager getInsightDataManager(){
nombre sugerido `getInstance()` (por singleton pattern)

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    public HttpResponse callTrafficLight() {
no debería ser `public`

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +                sendDataDeadlineMillis = System.currentTimeMillis() + (Math.abs(trafficLight.getSendTTL()) * 1000);
esto se puede hacer fuera del try-catch y de paso tampoco lo hace getDefaultResponse()

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    public Boolean isInsightMetricsEnable(String url){
le agregaría el comentario sobre la lógica de decisión sobre si la url está o no en la white-list.
(traer el comment del modulo de android)

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    static final String HEADER_X_INSIGHTS_DATA = "X-Insights-Data";
como tenemos un httpClient exclusivo para hablar con el backend, este header no lo necesitamos

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            BusinessFlowInfo.Builder businessFlowInfoBuilder = new BusinessFlowInfo.Builder()
para `business-flow-info`, ver como está resuelto en https://github.com/mercadolibre/fury_mp-config-provider-android/blob/develop/networking-configurer/src/main/java/com/mercadolibre/networking_configurer/restclient/configurator/decorator/client/insights/InsightsDataManager.java#L595

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            EventInfo eventInfo = new EventInfo.Builder().withName(request.getLastHeader(HEADER_X_INSIGHTS_EVENT_NAME)!=null?request.getLastHeader(HEADER_X_INSIGHTS_EVENT_NAME).getValue():"Unknown").
solo mandaría `event-info` si `event-name` tiene valor

2020-01-31 15:56 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    public TrafficLightResponse getTrafficLightResponse(){
no debería ser `public`

2020-01-31 20:29 UTC, rkuzner requested changes

2020-01-31 20:29 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            String modelName = System.getProperty("os.arch")!=null?System.getProperty("os.arch"):"";
este valor va sobre el cpu-type junto a cantidad de CPUs

2020-01-31 20:29 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    private static void getDefaultResponse() {
no debe ser `static`

2020-01-31 20:29 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    private static String getMemorySize() {
no es necesario que sea `static`

2020-01-31 20:29 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            int availableCPU = Runtime.getRuntime().availableProcessors();
todos los valores del dispositivo podrías calcularlos una sola vez y guardarlos en variables privadas para luego usarlos todas la veces que necesites

2020-01-31 20:51 UTC, rafgod-ML commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    public HttpResponse callTrafficLight() {
Lo deje public porque la estructura de test no es la misma y solo puedo usarlo public para el junit

2020-01-31 20:51 UTC, rafgod-ML commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +                sendDataDeadlineMillis = System.currentTimeMillis() + (Math.abs(trafficLight.getSendTTL()) * 1000);
listo

2020-01-31 20:51 UTC, rafgod-ML commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            BusinessFlowInfo.Builder businessFlowInfoBuilder = new BusinessFlowInfo.Builder()
listo

2020-01-31 20:51 UTC, rafgod-ML commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            EventInfo eventInfo = new EventInfo.Builder().withName(request.getLastHeader(HEADER_X_INSIGHTS_EVENT_NAME)!=null?request.getLastHeader(HEADER_X_INSIGHTS_EVENT_NAME).getValue():"Unknown").
listo

2020-01-31 20:52 UTC, rafgod-ML commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +    public Boolean isInsightMetricsEnable(String url){
listo

2020-01-31 21:24 UTC, rkuzner requested changes

2020-01-31 21:24 UTC, rkuzner commented on src/main/java/com/mercadopago/insight/InsightDataManager.java
> +            memorySize = "RAM Size " + memSize + " Bytes";
por favor, mandá solo el valor en bytes (sin el texto de "ram size" ni "bytes")

2020-01-31 22:31 UTC, rkuzner approved these changes

2020-02-03 12:51 UTC, delias-silva approved these changes

2020-02-03 12:51 UTC, merged