Created getPaymentMethods()
mercadopago/sdk-java pull request #142
Opened 2021-09-13 13:55 UTC by rhames07

## Cambios realizados para el feature:
 * Creación del método getPaymentMethods().

## Cambios generales
 * Adición de recursos relacionados con los métodos de pago.
 * Pruebas agregadas para el método creado.

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2021-09-13 14:13 UTC, delias-silva requested changes

2021-09-13 14:13 UTC, delias-silva commented on src/main/java/com/mercadopago/MercadoPago.java
> +        /**
Acho melhor seguirmos o padrão atual da SDK e os métodos na própria classe de resource.
Dá uma olhada na classe de Payments.

2021-09-13 16:04 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPago.java
> +        /**
Feito Danilo. Criei um método getAll() dentro do resource.

2021-09-13 17:18 UTC, delias-silva requested changes

2021-09-13 17:18 UTC, delias-silva commented on src/main/java/com/mercadopago/resources/PaymentMethod.java
> +public class PaymentMethod {
Se extender a classe `MPBase`, você tem acesso a vários métodos e vai simplificar a implementação.
Vejo o exemplo em [Payments](https://github.com/mercadopago/sdk-java/blob/master/src/main/java/com/mercadopago/resources/Payment.java#L32).

2021-09-13 17:18 UTC, delias-silva commented on src/main/java/com/mercadopago/resources/PaymentMethod.java
> +  public static List<PaymentMethod> getAll() throws MPRestException {
Aqui é possível usar uma anotação e simplificar a chamada da API.
[Exemplo](https://github.com/mercadopago/sdk-java/blob/master/src/main/java/com/mercadopago/resources/Payment.java#L702).

2021-09-13 17:55 UTC, rhames07 commented on src/main/java/com/mercadopago/resources/PaymentMethod.java
> +public class PaymentMethod {
Feito Danilo, realmente facilitou bastante, valeu!

2021-09-13 17:56 UTC, rhames07 commented on src/main/java/com/mercadopago/resources/PaymentMethod.java
> +  public static List<PaymentMethod> getAll() throws MPRestException {
Feito ✅

2021-09-13 18:03 UTC, delias-silva requested changes

2021-09-13 18:03 UTC, delias-silva commented on src/main/java/com/mercadopago/resources/PaymentMethod.java
> +  public static MPResourceArray all() throws MPException {
Só ficou faltando fazer adicionar um overload desse método com um parâmetro `MPRequestOptions`.

2021-09-13 18:28 UTC, rhames07 commented on src/main/java/com/mercadopago/resources/PaymentMethod.java
> +  public static MPResourceArray all() throws MPException {
Feito Danilo ✅

2021-09-27 13:27 UTC, delias-silva requested changes

2021-09-27 13:27 UTC, delias-silva commented on src/test/java/mercadopago/helper/MockHelper.java
> +  public static JsonElement setMockRequestPayload(String mockFile) throws IOException {
O nome desse método poderia ser diferente.
Ele não seta nada, pelo contrário retorna um JsonElement.

2021-09-27 13:27 UTC, delias-silva commented on src/test/java/mercadopago/helper/MockHelper.java
> +      boolean exists = false;
Além de validar se o header existe, também deveria validar se o valor dele está correto.
Por exemplo, o header `Authorization` deve conter `Bearer ACCESS_TOKEN`.

2021-09-27 13:27 UTC, delias-silva commented on src/test/java/mercadopago/helper/MockHelper.java
> +      for (Header header : headers) {
Se não me engano existe um método `containsHeader` que poderia ser usado.

2021-09-27 13:27 UTC, delias-silva commented on src/test/java/mercadopago/mock/HttpClientMock.java
> +  public void mock(String payload, int statusCode, String request) throws IOException {
Os nomes dos parâmetros estão um pouco confusos.
`payload` poderia ser `mockedResponseFile`.
`request` poderia ser `requestToCompareFile`.
Ou algo semelhante.

2021-09-27 13:27 UTC, delias-silva commented on src/test/java/mercadopago/resources/PaymentTest.java
> +    httpClientMock.mock(PAYMENT_BASE_JSON, HTTP_STATUS_CREATED, PAYMENT_BASE_JSON);
Acredito que não deveria usar o mesmo arquivo para o request e para o response.
Geralmente esses payloads são diferentes. No response tem mais informação.

2021-09-27 15:15 UTC, rhames07 commented on src/test/java/mercadopago/helper/MockHelper.java
> +  public static JsonElement setMockRequestPayload(String mockFile) throws IOException {
Alterado para "generateJsonElement".

2021-09-27 15:16 UTC, rhames07 commented on src/test/java/mercadopago/helper/MockHelper.java
> +      boolean exists = false;
Concordo. Validações realizadas.

2021-09-27 15:17 UTC, rhames07 commented on src/test/java/mercadopago/helper/MockHelper.java
> +      for (Header header : headers) {
Bem observado, o código ficou muito mais limpo. Valeu!

2021-09-27 15:17 UTC, rhames07 commented on src/test/java/mercadopago/mock/HttpClientMock.java
> +  public void mock(String payload, int statusCode, String request) throws IOException {
Feito.

2021-09-27 15:22 UTC, rhames07 commented on src/test/java/mercadopago/resources/PaymentTest.java
> +    httpClientMock.mock(PAYMENT_BASE_JSON, HTTP_STATUS_CREATED, PAYMENT_BASE_JSON);
O nome dos arquivos são o mesmo, mas são arquivos diferentes. Na classe "MockHelper", que é a responsável por fazer a leitura desses arquivos, existe o caminho dos diretórios de request e response, então sempre se é usado o arquivo correto.

2021-09-28 12:09 UTC, delias-silva approved these changes

2021-09-28 13:05 UTC, merged