Added v2 base
mercadopago/sdk-java pull request #153
Opened 2022-01-05 17:40 UTC by rhames07

## Cambios realizados para el feature:
* Novo arquivo de configuração da SDK (MercadoPagoConfig).
* Novo http client padrão (MPDefaultHttpClient).
* Novas classes auxiliares da camada net.
* Modificações em exceções já existentes e adição de nova exceção.
* Atualização de libs e plugins.

## Cambios generales
* Esta é apenas a nova base feita para receber a v2, as funcionalidades da v1 foram mantidas e serão substituídas para as novas configurações da v2 gradualmente até que a SDK esteja completamente refatorada.
* Nenhum teste foi adicionado; será testado no próximo PR com a implementação das funcionalidades de Payments por meio de testes de integração.

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [ ] Tests de mi funcionalidad 
- [ ] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-01-05 17:44 UTC, gdeandradero commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +public class MercadoPagoConfig {
nessa classe não da para usar lombok?

2022-01-05 18:03 UTC, delias-silva requested changes

2022-01-05 18:03 UTC, delias-silva commented on src/main/java/com/mercadopago/net/MPRequest.java
> +        this.headers = headers;
Se o parâmetro `headers` for `null` vai ocorrer um `NullPointerException` no método `addHeader`.
Seria bom verificar isso e setar um valor default.

2022-01-05 18:03 UTC, delias-silva commented on src/main/java/com/mercadopago/net/MPResource.java
> +        setResponse(null);
Não entendi a necessidade de setar null no `response` no construtor.

2022-01-05 18:03 UTC, delias-silva commented on src/main/java/com/mercadopago/net/MPResource.java
> +@Getter
`@Data` não cabe aqui?

2022-01-05 18:03 UTC, delias-silva commented on src/main/java/com/mercadopago/net/MPDefaultIHttpClient.java
> +        ConsoleHandler consoleHandler = new ConsoleHandler();
Dúvida: não deveria ser possível o integrador escolher se os logs serão feitos em arquivo, console, etc?

2022-01-05 18:03 UTC, delias-silva commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    private static final String DEFAULT_BASE_URL = "https://api.mercadopago.com";
É bom dar uma validada se todas essas constantes e variáveis estão sendo usadas e se fazem sentido.
Por exemplo `clientSecret` não é usado em nenhum lugar.

2022-01-05 18:03 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +public class MercadoPagoConfig {
Com certeza, vou colocar, valeu!

2022-01-05 18:37 UTC, eltinMeli reviewed
Rhames bom configurar google java formatter para ajustar as indentações e formatar com padrão que estamos adotando em outros projetos.

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPRequest.java
> +    }
Espaço entre os construtores

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/serialization/Serializer.java
> +        .create();
```suggestion
public class Serializer {
    
    private static final String DATE_FORMAT_ISO8601 = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";
    
    private static final Gson gson = new GsonBuilder()
        .setDateFormat(DATE_FORMAT_ISO8601)
        .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
        .create();
```

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPResponse.java
> +}
```suggestion
@Getter
@AllArgsConstructor
public class MPResponse {

    private final Integer statusCode;

    private final Map<String, List<String>> headers;

    private final String content;
    
}
```

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    }
Vazio?

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    private static final String TRACKING_ID = String.format("platform:%s,type:SDK%s,so;", getJavaVersion(System.getProperty("java.runtime.version")), CURRENT_VERSION);
Ao invés de ter métodos estáticos publicos, deixe  a propriedade publica.

```suggestion
    public static final String CURRENT_VERSION = "1.11.0";
    public static final String PRODUCT_ID = "BC32A7VTRPP001U8NHJ0";
    public static final String CLIENT_NAME = "MercadoPago-SDK-Java";
    public static final String TRACKING_ID = String.format("platform:%s,type:SDK%s,so;", getJavaVersion(System.getProperty("java.runtime.version")), CURRENT_VERSION);
```

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    private static final String CURRENT_VERSION = "1.11.0";
Necessário essa versão?
```suggestion
    private static final String CURRENT_VERSION = "2.0.0";
```

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    }
Ao colocar as propriedades estáticas publicas pode limar isso

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    }
Lima isso

2022-01-05 18:37 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPDefaultIHttpClient.java
> +        }
```suggestion
        if (Objects.nonNull(MercadoPagoConfig.getProxy())) {
            httpClientBuilder.setProxy(MercadoPagoConfig.getProxy());
        }

        if (Objects.nonNull(MercadoPagoConfig.getRetryHandler())) {
            httpClientBuilder.setRetryHandler(MercadoPagoConfig.getRetryHandler());
        
        } else {
            DefaultHttpRequestRetryHandler retryHandler = new DefaultHttpRequestRetryHandler(DEFAULT_RETRIES, false);
            httpClientBuilder.setRetryHandler(retryHandler);
        }
```

2022-01-06 11:22 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPRequest.java
> +        this.headers = headers;
Adicionado anotação Lombok para construtor; adicionado tratamento to método addHeader.

2022-01-06 11:23 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPResource.java
> +        setResponse(null);
Removido.

2022-01-06 11:23 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPResource.java
> +@Getter
Feito.

2022-01-06 11:39 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    private static final String DEFAULT_BASE_URL = "https://api.mercadopago.com";
Feito.

2022-01-06 11:39 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPRequest.java
> +    }
Feito.

2022-01-06 11:39 UTC, rhames07 commented on src/main/java/com/mercadopago/serialization/Serializer.java
> +        .create();
Feito.

2022-01-06 11:40 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPResponse.java
> +}
Feito.

2022-01-06 11:41 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    }
Passou batido no ctrl c + ctrl v, método removido.

2022-01-06 11:41 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    private static final String TRACKING_ID = String.format("platform:%s,type:SDK%s,so;", getJavaVersion(System.getProperty("java.runtime.version")), CURRENT_VERSION);
Feito.

2022-01-06 11:41 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    private static final String CURRENT_VERSION = "1.11.0";
Realmente não, removido.

2022-01-06 11:41 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    }
Feito.

2022-01-06 11:42 UTC, rhames07 commented on src/main/java/com/mercadopago/MercadoPagoConfig.java
> +    }
Feito.

2022-01-06 11:42 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPDefaultIHttpClient.java
> +        }
Feito.

2022-01-06 11:46 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPDefaultIHttpClient.java
> +        ConsoleHandler consoleHandler = new ConsoleHandler();
Foi adicionada a propriedade loggingHandler na classe MercadoPagoConfig, o que permitiram que o integrador insira o StreamHandler de sua opção, e caso não seja inserido, a classe MPDefaultHttpClient usará o ConsoleHandler de forma padrão.

2022-01-06 12:07 UTC, delias-silva commented on src/main/java/com/mercadopago/net/MPRequest.java
> +@AllArgsConstructor
Realmente vai usar o construtor com todos os argumentos?

2022-01-06 12:08 UTC, delias-silva commented on src/main/java/com/mercadopago/net/MPRequest.java
> +    this.payload = null;
Não é necessário setar null no construtor.

2022-01-06 12:16 UTC, rhames07 commented on src/main/java/com/mercadopago/net/MPRequest.java
> +@AllArgsConstructor
Creio que na implementação do MercadoPagoClient (ainda à ser implementado) vamos utilizar, levando em consideração a implementação da poc, mas vou retirar e caso haja a necessidade adiciono novamente.

2022-01-06 18:11 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/exceptions/MPValidationException.java
> +  private Collection<ValidationViolation> colViolations = null;
só chamar de violations não seria mais simples?

2022-01-06 18:18 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/net/MPDefaultHttpClient.java
> +        response = new BasicHttpResponse(new BasicStatusLine(completeRequest.getProtocolVersion(), 404, null));
Acho que 500 seria um status code melhor pra esse caso

2022-01-06 18:21 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/net/MPDefaultHttpClient.java
> +      throw new MPMalformedRequestException("HttpMethod must be \"GET\", \"POST\", \"PUT\" or \"DELETE\".");
```suggestion
      throw new MPMalformedRequestException("HttpMethod must be either \"GET\", \"POST\", \"PUT\" or \"DELETE\".");
```

2022-01-06 18:23 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/net/MPRestClient.java
> +     * Create a IHttpClient
```suggestion
     * Create a MPHttpClient
```

2022-01-06 18:24 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/net/MPRestClient.java
> +     * @return a IHttpClient
```suggestion
     * @return a MPHttpClient
```

2022-01-06 18:24 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/net/MPRestClient.java
> +     * Returns the HttpRequestBase to be used by the IHttpClient.
```suggestion
     * Returns the HttpRequestBase to be used by MPHttpClient.
```

2022-01-06 18:46 UTC, romerosilva-meli commented
Acho que vale remover a classe `MercadoPago` logo também

2022-01-06 19:05 UTC, eltinMeli requested changes

2022-01-06 19:05 UTC, eltinMeli commented on src/main/java/com/mercadopago/exceptions/MPValidationException.java
> +        !colViolations.isEmpty()) {
```suggestion
    if (CollectionUtils.isNotEmpty(colViolations)) {
```

2022-01-06 19:05 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPDefaultHttpClient.java
> +      return mpResponse;
```suggestion
      return new MPResponse(response.getStatusLine().getStatusCode(), headers, responseBody);
```

2022-01-06 19:05 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPDefaultHttpClient.java
> +    return entity;
```suggestion
  private HttpEntity normalizePayload(JsonObject payload) throws MPMalformedRequestException {
    if (payload != null && payload.size() != 0) {
      try {
        return new StringEntity(payload.toString(), "UTF-8");
      } catch (Exception ex) {
        throw new MPMalformedRequestException(ex);
      }
    }

    return null;
```

2022-01-06 19:05 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPDefaultHttpClient.java
> +        .disableRedirectHandling();
```suggestion
    PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager(registry);
    connectionManager.setMaxTotal(MercadoPagoConfig.getMaxConnections());
    connectionManager.setDefaultMaxPerRoute(MercadoPagoConfig.getMaxConnections());
    connectionManager.setValidateAfterInactivity(VALIDATE_INACTIVITY_INTERVAL_MS);

    HttpClientBuilder httpClientBuilder = HttpClients.custom()
        .setConnectionManager(connectionManager)
        .setKeepAliveStrategy(new KeepAliveStrategy())
        .disableCookieManagement()
        .disableRedirectHandling();
```

2022-01-06 19:05 UTC, eltinMeli commented on src/main/java/com/mercadopago/net/MPDefaultHttpClient.java
> +    }
Não entendi o sentido desse for, ele tá inserindo um item caso a lista de origem não contenha item. Validando se a set funcionou...tipo estou validando se minha copia tem todos os itens

2022-01-06 20:26 UTC, rhames07 commented on src/main/java/com/mercadopago/exceptions/MPValidationException.java
> +  private Collection<ValidationViolation> colViolations = null;
Essa é uma exception da v1 que pelo menos nesse primeiro momento não vejo utilidade na nova estrutura da v2, será deletada após a implementação da camada de client.

2022-01-06 20:26 UTC, rhames07 commented on src/main/java/com/mercadopago/exceptions/MPValidationException.java
> +        !colViolations.isEmpty()) {
Essa é uma exception da v1 que pelo menos nesse primeiro momento não vejo utilidade na nova estrutura da v2, será deletada após a implementação da camada de client.

2022-01-07 12:40 UTC, delias-silva approved these changes

2022-01-07 12:41 UTC, merged