Refactor IdempotentRequest to builder pattern
mercadopago/sdk-java pull request #159
Opened 2022-01-21 12:49 UTC by rhames07

## Cambios realizados para el feature:
 * Refactor IdempotentRequest to builder pattern.
 * Refactor of MercadoPagoClient to use request's builder.
 * Tests adapted to the new pattern.

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-01-21 17:57 UTC, romerosilva-meli requested changes

2022-01-21 17:57 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/IdempotentRequest.java
> +import lombok.experimental.SuperBuilder;
Entendo a motivação, mas acho melhor evitarmos usar uma classe experimental.

2022-01-21 17:57 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +  private int addCustomSocketTimeout(MPRequestOptions requestOptions) {
acho que faria mais sentido ter um método só `addSocketTimeout(MPRequest request, MPRequestOptions requestOptions)`, o que acha?

2022-01-21 17:57 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +  private int addCustomConnectionTimeout(MPRequestOptions requestOptions) {
veja acima, mesma idéia do socket timeout

2022-01-21 17:57 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +  private int addCustomConnectionRequestTimeout(MPRequestOptions requestOptions) {
veja acima, mesma idéia do socket timeout

2022-01-24 13:47 UTC, rhames07 commented on src/main/java/com/mercadopago/client/IdempotentRequest.java
> +import lombok.experimental.SuperBuilder;
Concordo. Alterei para uma maneira no qual tive que usar um construtor, que não era o que eu gostaria mas é o que o lombok permite de maneira oficial até então.

2022-01-24 13:47 UTC, rhames07 commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +  private int addCustomSocketTimeout(MPRequestOptions requestOptions) {
Boa ideia, feito.

2022-01-24 13:47 UTC, rhames07 commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +  private int addCustomConnectionTimeout(MPRequestOptions requestOptions) {
Feito.

2022-01-24 13:47 UTC, rhames07 commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +  private int addCustomConnectionRequestTimeout(MPRequestOptions requestOptions) {
Feito.

2022-01-24 18:24 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/IdempotentRequest.java
> +          IdempotentRequest.idempotentBuilder()
Aqui não tem excesso de indentação?

2022-01-24 18:31 UTC, rhames07 commented on src/main/java/com/mercadopago/client/IdempotentRequest.java
> +          IdempotentRequest.idempotentBuilder()
O google-java-format indentou assim, e eu particularmente não achei que ficou ruim, mas depois podemos revisar suas configurações, o que acha?

2022-01-24 18:47 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +          String.format("Error while trying to add query string to path: %s", e.getMessage()));
Essa lógica poderia estar dentro do `UrlFormatter.format`. O que acha?

2022-01-24 18:47 UTC, romerosilva-meli commented on src/test/java/mercadopago/client/CustomerCardClientTest.java
>      this.mpHttpClient = new MPDefaultHttpClientMock(httpClientMock);
Essas linhas podem ser removidas

2022-01-24 19:29 UTC, rhames07 commented on src/main/java/com/mercadopago/client/MercadoPagoClient.java
> +          String.format("Error while trying to add query string to path: %s", e.getMessage()));
Feito.

2022-01-24 19:29 UTC, rhames07 commented on src/test/java/mercadopago/client/CustomerCardClientTest.java
>      this.mpHttpClient = new MPDefaultHttpClientMock(httpClientMock);
Feito.

2022-01-24 19:53 UTC, romerosilva-meli approved these changes

2022-01-24 19:53 UTC, merged