Add Preapproval
mercadopago/sdk-java pull request #166
Opened 2022-01-28 19:02 UTC by rhames07

## Cambios realizados para el feature:
* Add preapproval

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-01-28 21:17 UTC, lucmantovani commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringCreateRequest.java
> +  private final String startDate;
```suggestion
  /** Recurring start date. Must follow the pattern ("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") */
  private final String startDate;
```
Seria melhor utilizar o tipo Date e o Serializer se encarregar de garantir o formato ao interagir com a API?

2022-01-28 21:17 UTC, lucmantovani commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringCreateRequest.java
> +  private final String endDate;
```suggestion
  /** Recurring end date. Must follow the pattern ("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") */
  private final String endDate;
```

Mesma ideia aqui

2022-01-31 13:30 UTC, delias-silva commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringCreateRequest.java
> +  private final String startDate;
O ideal é usar o framework `java.time` que foi introduzido no java 8.
Nele tem novas classe como `LocalDateTime` e `OffsetDateTime`. Para o nosso caso acredito que `OffsetDateTime` é melhor.
Dá uma olhada nesse [tutorial](https://docs.oracle.com/javase/tutorial/datetime/TOC.html) da Oracle.
Obs: Talvez tenha que configurar o Gson para funcionar corretamente com esses tipos.

2022-01-31 21:21 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringUpdateRequest.java
> +  private final Date startDate;
Levando em conta https://github.com/mercadopago/sdk-java/pull/166/files#r795670291 deveriamos manter o mesmo tipo usado em `PreApprovalAutoRecurringCreateRequest`

2022-01-31 21:22 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringUpdateRequest.java
> +  private final Date endDate;
Mesma coisa que o comentário acima

2022-01-31 21:34 UTC, romerosilva-meli requested changes

2022-01-31 21:34 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/preapproval/PreapprovalClient.java
> +        send("/preapproval", HttpMethod.POST, serializeToJson(request), null, requestOptions);
Aqui não é necessário ser um `IdempotentRequest`?

2022-01-31 21:34 UTC, romerosilva-meli commented on src/main/java/com/mercadopago/client/preapproval/PreapprovalClient.java
> +            requestOptions);
Aqui não é necessário ser um IdempotentRequest?

2022-01-31 21:34 UTC, romerosilva-meli commented on src/test/java/mercadopago/client/preapproval/PreapprovalClientTest.java
> +  void getSuccessSuccess() throws IOException, MPException {
```suggestion
  void getSuccess() throws IOException, MPException {
```

2022-02-01 13:07 UTC, rhames07 commented on src/main/java/com/mercadopago/client/preapproval/PreapprovalClient.java
> +        send("/preapproval", HttpMethod.POST, serializeToJson(request), null, requestOptions);
Me baseei na SDK dotnet v2, onde só se é usado o `IdempotentRequest` para `Payments` e `AdvancedPayments`. Acha que para o caso de `Preapproval` é melhor usar `IdempotentRequest` para essas requisições?

2022-02-01 13:16 UTC, rhames07 commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringCreateRequest.java
> +  private final String startDate;
Por enquanto mantive o tipo Date para todas as datas e fiz um ajuste no serializer para que o formato parseado seja compatível com a api de preapproval e as demais. Ainda nessa sprint vamos debater sobre esse tema e definir como vamos ser em relação ao tratamento de datas em outro PR.

2022-02-01 13:16 UTC, rhames07 commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringCreateRequest.java
> +  private final String endDate;
Comentário removido. Não terá mais a necessidade de informar o padrão após ajustes no serializer.

2022-02-01 13:17 UTC, rhames07 commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringUpdateRequest.java
> +  private final Date startDate;
Feito. Todos as classes usarão o tipo Date por enquanto.

2022-02-01 13:17 UTC, rhames07 commented on src/main/java/com/mercadopago/client/preapproval/PreApprovalAutoRecurringUpdateRequest.java
> +  private final Date endDate;
Feito.

2022-02-01 13:17 UTC, rhames07 commented on src/test/java/mercadopago/client/preapproval/PreapprovalClientTest.java
> +  void getSuccessSuccess() throws IOException, MPException {
Feito.

2022-02-01 17:10 UTC, romerosilva-meli approved these changes

2022-02-01 17:16 UTC, merged