Refactor MPRequest
mercadopago/sdk-java pull request #168
Opened 2022-02-01 17:57 UTC by rhames07

## Cambios realizados para el feature:
 * Delete IdempotentRequest.
 * Refactor MPRequest.
 
## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-02-01 18:27 UTC, romerosilva-meli requested changes

2022-02-01 18:27 UTC, romerosilva-meli commented on src/test/java/mercadopago/client/MercadoPagoClientTest.java
> -  public void sendIdempotentRequestWithBodySuccess() throws IOException, MPException {
acho que a gente poderia substiuir esse teste por outro verificando se o header X-Idempotent-Request é incluído quando o método é POST

2022-02-01 18:48 UTC, rhames07 commented on src/test/java/mercadopago/client/MercadoPagoClientTest.java
> -  public void sendIdempotentRequestWithBodySuccess() throws IOException, MPException {
Feito.

2022-02-02 13:02 UTC, romerosilva-meli commented on src/test/java/mercadopago/client/MercadoPagoClientTest.java
> +  public void sendWithIdempotentHeader() throws IOException, MPException {
```suggestion
  public void sendWithIdempotentHeaderIfMethodIsPost() throws IOException, MPException {
```

2022-02-02 13:29 UTC, rhames07 commented on src/test/java/mercadopago/client/MercadoPagoClientTest.java
> +  public void sendWithIdempotentHeader() throws IOException, MPException {
Feito.

2022-02-02 13:33 UTC, romerosilva-meli approved these changes

2022-02-02 13:34 UTC, merged