Adjust README.md for v2
mercadopago/sdk-java pull request #190
Opened 2022-02-16 11:30 UTC by rhames07

## Cambios realizados para el feature:
 * Adjust README.md

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-02-16 13:14 UTC, lucmantovani commented on README.md
> +3. Copy the access_token in the [credentials](https://www.mercadopago.com/mlb/account/credentials) section of the page
```suggestion
3. Copy the access_token in the [credentials](https://www.mercadopago.com/developers/panel) section of the page
```
Com esse link a pessoa é redirecionada ao site correto do país, não deixando fixo mlb

2022-02-16 13:14 UTC, lucmantovani commented on README.md
> +  / [Spanish](https://www.mercadopago.com.br/developers/es/reference)
```suggestion
- Mercado Pago reference API. [Portuguese](https://www.mercadopago.com/developers/pt/reference)
  / [English](https://www.mercadopago.com/developers/en/reference)
  / [Spanish](https://www.mercadopago.com/developers/es/reference)
```
Com esse link a pessoa é redirecionada ao site correto do país, não deixando fixo mlb

2022-02-16 13:14 UTC, lucmantovani commented on README.md
> +at [developers.mercadopago.com](https://developers.mercadopago.com)
```suggestion
at our developers site:  [English](https://www.mercadopago.com/developers/en/support/center/contact) / [Portuguese](https://www.mercadopago.com/developers/pt/support/center/contact) / [Spanish](https://www.mercadopago.com/developers/es/support/center/contact)
```
Assim deixamos o link direto para abertura do ticket, já que o texto diz para contactar o time de suporte.

2022-02-16 13:14 UTC, lucmantovani commented on README.md
> +# Mercado Pago SDK v2 for Java
Acho que eu deixaria sem o "v2".
A versão já vai ser exibida pela tag definida mais abaixo, e as outras SDKs (Ruby, Python e .NET)  também não especificam a versão no título.

2022-02-16 14:00 UTC, rhames07 commented on README.md
> +# Mercado Pago SDK v2 for Java
Feito.

2022-02-16 14:00 UTC, rhames07 commented on README.md
> +at [developers.mercadopago.com](https://developers.mercadopago.com)
Feito.

2022-02-16 14:00 UTC, rhames07 commented on README.md
> +  / [Spanish](https://www.mercadopago.com.br/developers/es/reference)
Feito.

2022-02-16 14:00 UTC, rhames07 commented on README.md
> +3. Copy the access_token in the [credentials](https://www.mercadopago.com/mlb/account/credentials) section of the page
Feito.

2022-02-16 14:04 UTC, delias-silva commented on README.md
> +The official [Mercado Pago](https://www.mercadopago.com.br/developers/pt/guides) Java client library.
Aqui também é necessário mudar a URL. Como tem o idioma no path, o melhor é usar inglês.
https://www.mercadopago.com/developers/en/guides

2022-02-16 14:16 UTC, delias-silva commented
Para seguir as melhores práticas de repositórios open source é importante adicionar uma seção Contributing.
[Aqui](https://github.com/mercadopago/sdk-python#-contributing) no SDK de Python tem o exemplo.
Nele tem um link para o [CONTRIBUTING.md](https://github.com/mercadopago/sdk-python/blob/master/CONTRIBUTING.md), que por sua vez tem o [CODING_GUIDELINES.md](https://github.com/mercadopago/sdk-python/blob/master/CODING_GUIDELINES.md).
Seria necesario também adicionar esses arquivos.

2022-02-16 19:02 UTC, rhames07 commented on README.md
> +The official [Mercado Pago](https://www.mercadopago.com.br/developers/pt/guides) Java client library.
Feito.

2022-02-16 21:00 UTC, delias-silva approved these changes

2022-02-16 21:27 UTC, romerosilva-meli requested changes

2022-02-16 21:27 UTC, romerosilva-meli commented on README.md
> +You can make your own http client instead of using our `MPDefaultHttpClient` since it implements our `MPHttpClient`
```suggestion
You can use a custom http client instead of using the default `MPDefaultHttpClient` by implementing the `MPHttpClient`
```

2022-02-16 21:27 UTC, romerosilva-meli commented on README.md
> +    }
```suggestion
    } catch (MPApiException ex) {
      System.out.printf(
          "MercadoPago Error. Status: %s, Content: %s%n",
          ex.getApiResponse().getStatusCode(), ex.getApiResponse().getContent());
    } catch (MPException ex) {
      ex.printStackTrace();
    }
```

2022-02-16 21:27 UTC, romerosilva-meli commented on README.md
> +## 🤝 Contributing
Acho que seria bom incluir aqui uma explicação de que existe a dependência do docker pra desenvolvimento e que temos pre-commit hooks que rodam linter e formatador de código (incluir links para ambos).

2022-02-17 11:26 UTC, rhames07 commented on README.md
> +You can make your own http client instead of using our `MPDefaultHttpClient` since it implements our `MPHttpClient`
Feito.

2022-02-17 11:26 UTC, rhames07 commented on README.md
> +    }
Feito.

2022-02-17 11:27 UTC, rhames07 commented on README.md
> +## 🤝 Contributing
Informação inserida ao `CODING_GUIDELINS.md` junto às instruções para uso do pre-commit.

2022-02-18 17:18 UTC, romerosilva-meli approved these changes

2022-02-18 17:26 UTC, merged