Add card token integration test
mercadopago/sdk-java pull request #196
Opened 2022-02-22 12:29 UTC by rhames07

## Cambios realizados para el feature:
 *Add card token integration test
 
## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-02-22 20:16 UTC, romerosilva-meli requested changes

2022-02-22 20:16 UTC, romerosilva-meli commented on src/test/java/com/mercadopago/BaseClientIT.java
> +
Aqui seria melhor receber o accessToken por variável de ambiente. 

É importante cancelar esse access token para que ele não possa ser usado também.

2022-02-22 20:16 UTC, romerosilva-meli commented on src/test/java/com/mercadopago/BaseClientIT.java
> +    MercadoPagoConfig.setHttpClient(null);
O `getHttpClient` já se encarrega de instanciar `MPDefaultHttpClient` caso `httpClient` seja nulo
```suggestion
```

2022-02-22 20:25 UTC, rhames07 commented on src/test/java/com/mercadopago/BaseClientIT.java
> +    MercadoPagoConfig.setHttpClient(null);
Certo, porém os testes unitários instanciam um http client (mock), e se não settarmos como nulo antes do teste de integração corre o risco dele não estar nulo caso um teste unitário seja executado antes.

2022-02-24 19:19 UTC, romerosilva-meli commented on src/test/java/com/mercadopago/BaseClientIT.java
> +  protected static final String accessToken = System.getenv("ACCESS_TOKEN");
```suggestion
  protected static final String accessToken = System.getenv("MP_ACCESS_TOKEN");
```
Pode ser que o integrador precise usar mais de um access token

2022-02-24 20:34 UTC, romerosilva-meli approved these changes

2022-02-24 20:57 UTC, merged