Add MerchantOrderClientIT
mercadopago/sdk-java pull request #203
Opened 2022-03-02 14:14 UTC by rhames07

## Cambios realizados para el feature:
 * Add merchant order integration test

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2022-03-02 17:38 UTC, romerosilva-meli requested changes

2022-03-02 17:38 UTC, romerosilva-meli commented on src/test/java/com/mercadopago/client/merchantorder/MerchantOrderClientIT.java
> +  private static final String PREFERENCE_ID = "798798399-13769cb5-b898-448f-8d5a-c939a8cee479";
não está sendo usado

2022-03-02 17:38 UTC, romerosilva-meli commented on src/test/java/com/mercadopago/client/merchantorder/MerchantOrderClientIT.java
> +  private static final long MERCHANT_ORDER_ID = 4018801790L;
não está sendo usado

2022-03-02 17:38 UTC, romerosilva-meli commented on src/test/java/com/mercadopago/client/merchantorder/MerchantOrderClientIT.java
> +  private static final OffsetDateTime DATE =
não está sendo usado

2022-03-02 18:10 UTC, rhames07 commented on src/test/java/com/mercadopago/client/merchantorder/MerchantOrderClientIT.java
> +  private static final String PREFERENCE_ID = "798798399-13769cb5-b898-448f-8d5a-c939a8cee479";
Feito.

2022-03-02 18:10 UTC, rhames07 commented on src/test/java/com/mercadopago/client/merchantorder/MerchantOrderClientIT.java
> +  private static final OffsetDateTime DATE =
Feito.

2022-03-02 18:10 UTC, rhames07 commented on src/test/java/com/mercadopago/client/merchantorder/MerchantOrderClientIT.java
> +  private static final long MERCHANT_ORDER_ID = 4018801790L;
Feito.

2022-03-04 13:38 UTC, romerosilva-meli approved these changes

2022-03-04 13:41 UTC, merged