Improvements for boleto (fees, fines and discount) and credit card payments (3DS 2.0)
mercadopago/sdk-java pull request #252
Opened 2023-02-22 16:55 UTC by romerosilva-meli

this branch adds:

- Data models for processing boletos with fees, fines and discount
- Fields for processing credit card payments with 3DS 2.0

## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2023-02-22 18:46 UTC, gdeandradero commented on src/main/java/com/mercadopago/resources/payment/Payment.java
> +  private PaymentThreeDSInfo threeDsinfo;
```suggestion
  private PaymentThreeDSInfo threeDsInfo;
```

2023-02-22 19:14 UTC, eltinMeli requested changes

2023-02-22 19:14 UTC, eltinMeli commented on src/main/java/com/mercadopago/resources/payment/Payment.java
> +  private PaymentThreeDSInfo threeDsinfo;
Tá certo esse camelCase para o retorno dessa propriedade?

2023-02-22 19:14 UTC, eltinMeli commented on src/main/java/com/mercadopago/resources/payment/PaymentDiscount.java
> +  private BigDecimal amountApplied;
Pode remover essa propriedade, foi removida pelo time de Core.

2023-02-22 19:14 UTC, eltinMeli commented on src/main/java/com/mercadopago/resources/payment/PaymentFee.java
> +  private BigDecimal amountApplied;
Pode remover essa propriedade, foi removida pelo time de Core.

2023-02-22 19:14 UTC, eltinMeli commented on src/test/java/com/mercadopago/resources/mocks/request/payment/payment_base.json
> +          "type":"fixed",
`fixed` não é suportado para fine
```suggestion
          "type":"percentage",
```

2023-02-22 19:14 UTC, eltinMeli commented on src/test/java/com/mercadopago/resources/mocks/request/payment/payment_base.json
> +          "type":"fixed",
`fixed` não é suportado para interest
```suggestion
          "type":"percentage",
```

2023-02-22 19:14 UTC, eltinMeli commented on src/test/java/com/mercadopago/client/payment/PaymentClientTest.java
> +        PaymentFeeRequest.builder().type("fixed").value(new BigDecimal(2)).build();
`fixed` não é suportado para fine
```suggestion
        PaymentFeeRequest.builder().type("percentage").value(new BigDecimal(2)).build();
```

2023-02-22 19:14 UTC, eltinMeli commented on src/test/java/com/mercadopago/client/payment/PaymentClientTest.java
> +        PaymentFeeRequest.builder().type("fixed").value(new BigDecimal("0.03")).build();
`fixed` não é suportado para interest
```suggestion
        PaymentFeeRequest.builder().type("percentage").value(new BigDecimal("0.03")).build();
```

2023-02-22 19:19 UTC, eltinMeli requested changes

2023-02-22 19:19 UTC, eltinMeli commented on src/test/java/com/mercadopago/resources/mocks/request/payment/payment_3ds.json
> +  },
Esses dados são relacionados a boleto com multa, creio que veio junto por engano para 3ds

2023-02-22 19:19 UTC, eltinMeli commented on src/main/java/com/mercadopago/resources/payment/Payment.java
> +  private PaymentThreeDSInfo threeDsinfo;
É isso msm Gabs pelo que está no json de mock.

"three_dsinfo"

2023-02-22 19:19 UTC, eltinMeli commented on src/main/java/com/mercadopago/resources/payment/Payment.java
> +  private PaymentThreeDSInfo threeDsinfo;
Conferi no mock e está correta

2023-02-27 12:37 UTC, rhames07 commented on src/main/java/com/mercadopago/resources/payment/Payment.java
> +  private PaymentThreeDSInfo threeDsinfo;
Para manter a congruência com a forma que estamos chamando 3DS, sempre com `DS` em maiúsculo, assim como da classe `PaymentThreeDSInfo`, não seria melhor chamar a variável de `threeDSInfo`? Realmente não sei o que seria mais correto nesse caso.

2023-02-27 12:38 UTC, rhames07 commented on src/main/java/com/mercadopago/resources/payment/Payment.java
> +  private PaymentThreeDSInfo threeDsinfo;
@eltinMeli

2023-02-27 12:45 UTC, rhames07 commented on src/main/java/com/mercadopago/resources/payment/PaymentThreeDSInfo.java
> +@Builder
O objeto instanciado dessa classe deverá ser apenas de leitura para o usuário, assim como os outros arquivos dentro de `/resources`, então não deveria ter o comportamento builder, certo?
```suggestion
```

2023-02-27 14:24 UTC, rhames07 approved these changes

2023-02-27 14:59 UTC, eltinMeli approved these changes

2023-02-28 17:51 UTC, merged