Add new fields required for PSE payments
mercadopago/sdk-java pull request #256
Opened 2023-05-25 13:23 UTC by romerosilva-meli

## Cambios realizados para el feature:
 * Add address and phone information to `PaymentPayerRequest` for PSE payments 
 
## Checklist validación PR:

- [X] Título y descripción clara del PR
- [X] Tests de mi funcionalidad 
- [X] Documentación de mi funcionalidad
- [X] Tests ejecutados y pasados
- [X] Branch Coverage >= 80%

2023-05-25 13:37 UTC, rhames07 approved these changes

2023-05-29 14:19 UTC, eltinMeli requested changes

2023-05-29 14:19 UTC, eltinMeli commented on src/test/java/com/mercadopago/resources/mocks/request/payment/payment_pse.json
> +      "number": "37462770865"
Trocar CPF para um ficticio

2023-05-29 19:45 UTC, eltinMeli approved these changes

2023-05-30 13:20 UTC, merged